<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_7tGLHHvService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.7tGLHHv' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Application/MessageHandler/CartEventHandler.php';

        return $container->privates['.messenger.handler_descriptor.7tGLHHv'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Nocart\Promotion\Application\MessageHandler\CartEventHandler(($container->privates['Nocart\\Promotion\\Domain\\Repository\\PromotionSessionRepositoryInterface'] ?? $container->load('getPromotionSessionRepositoryInterfaceService')), ($container->privates['logger'] ?? self::getLoggerService($container))), []);
    }
}
