<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplyPromoCodeHandlerService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Promotion\Application\Command\ApplyPromoCodeHandler' shared autowired service.
     *
     * @return \Nocart\Promotion\Application\Command\ApplyPromoCodeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Command/ApplyPromoCodeHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/PromotionRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemoryPromotionRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/EventPublisherInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/KafkaEventPublisher.php';

        return $container->privates['Nocart\\Promotion\\Application\\Command\\ApplyPromoCodeHandler'] = new \Nocart\Promotion\Application\Command\ApplyPromoCodeHandler(($container->privates['Nocart\\Promotion\\Domain\\Repository\\PromotionRepositoryInterface'] ??= new \Nocart\Promotion\Infrastructure\Persistence\InMemoryPromotionRepository()), ($container->privates['Nocart\\Promotion\\Domain\\Repository\\PromotionSessionRepositoryInterface'] ?? $container->load('getPromotionSessionRepositoryInterfaceService')), ($container->privates['Nocart\\SharedKernel\\Infrastructure\\Messaging\\EventPublisherInterface'] ??= new \Nocart\SharedKernel\Infrastructure\Messaging\KafkaEventPublisher($container->getEnv('KAFKA_BROKERS'))));
    }
}
