<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_MessengerDebugService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.messenger_debug' shared service.
     *
     * @return \Symfony\Component\Messenger\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Command/DebugCommand.php';

        $container->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['messenger.bus.default' => ['Nocart\\Promotion\\Application\\Command\\ApplyPromoCodeCommand' => [['Nocart\\Promotion\\Application\\Command\\ApplyPromoCodeHandler', []]], 'Nocart\\Promotion\\Application\\Command\\ApplyPromotionCommand' => [['Nocart\\Promotion\\Application\\Command\\ApplyPromotionHandler', []]], 'Nocart\\SharedKernel\\Infrastructure\\Messenger\\Message\\ExternalEventMessage' => [['Nocart\\Promotion\\Application\\MessageHandler\\CartEventHandler', []]], 'Nocart\\Promotion\\Application\\Query\\GetAvailablePromotionsQuery' => [['Nocart\\Promotion\\Application\\Query\\GetAvailablePromotionsHandler', []]], 'Nocart\\Promotion\\Application\\Query\\GetPromotionSessionQuery' => [['Nocart\\Promotion\\Application\\Query\\GetPromotionSessionHandler', []]], 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => [['console.messenger.execute_command_handler', ['sign' => true]]], 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => [['messenger.redispatch_message_handler', []]]]]);

        $instance->setName('debug:messenger');
        $instance->setDescription('List messages you can dispatch using the message buses');

        return $instance;
    }
}
