<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAvailablePromotionsHandlerService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Promotion\Application\Query\GetAvailablePromotionsHandler' shared autowired service.
     *
     * @return \Nocart\Promotion\Application\Query\GetAvailablePromotionsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetAvailablePromotionsHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/PromotionRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemoryPromotionRepository.php';

        return $container->privates['Nocart\\Promotion\\Application\\Query\\GetAvailablePromotionsHandler'] = new \Nocart\Promotion\Application\Query\GetAvailablePromotionsHandler(($container->privates['Nocart\\Promotion\\Domain\\Repository\\PromotionRepositoryInterface'] ??= new \Nocart\Promotion\Infrastructure\Persistence\InMemoryPromotionRepository()));
    }
}
