<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionControllergetAvailableService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FJUrFJ9.Nocart\Promotion\Ports\Http\PromotionController::getAvailable()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FJUrFJ9.Nocart\\Promotion\\Ports\\Http\\PromotionController::getAvailable()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Promotion\\Application\\Query\\GetAvailablePromotionsHandler', 'getGetAvailablePromotionsHandlerService', true],
        ], [
            'handler' => 'Nocart\\Promotion\\Application\\Query\\GetAvailablePromotionsHandler',
        ]))->withContext('Nocart\\Promotion\\Ports\\Http\\PromotionController::getAvailable()', $container);
    }
}
