<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionControllerapplyService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5QzEBg3.Nocart\Promotion\Ports\Http\PromotionController::apply()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5QzEBg3.Nocart\\Promotion\\Ports\\Http\\PromotionController::apply()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Promotion\\Application\\Command\\ApplyPromotionHandler', 'getApplyPromotionHandlerService', true],
        ], [
            'handler' => 'Nocart\\Promotion\\Application\\Command\\ApplyPromotionHandler',
        ]))->withContext('Nocart\\Promotion\\Ports\\Http\\PromotionController::apply()', $container);
    }
}
