<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionControllerapplyCodeService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VxGge0X.Nocart\Promotion\Ports\Http\PromotionController::applyCode()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VxGge0X.Nocart\\Promotion\\Ports\\Http\\PromotionController::applyCode()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Promotion\\Application\\Command\\ApplyPromoCodeHandler', 'getApplyPromoCodeHandlerService', true],
        ], [
            'handler' => 'Nocart\\Promotion\\Application\\Command\\ApplyPromoCodeHandler',
        ]))->withContext('Nocart\\Promotion\\Ports\\Http\\PromotionController::applyCode()', $container);
    }
}
