<?php

namespace ContainerPhhYfNg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionSessionRepositoryInterfaceService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Promotion\Domain\Repository\PromotionSessionRepositoryInterface' shared autowired service.
     *
     * @return \Nocart\Promotion\Infrastructure\Persistence\RedisPromotionSessionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/PromotionSessionRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/RedisPromotionSessionRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/RedisClientInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/PredisRedisClient.php';

        return $container->privates['Nocart\\Promotion\\Domain\\Repository\\PromotionSessionRepositoryInterface'] = new \Nocart\Promotion\Infrastructure\Persistence\RedisPromotionSessionRepository(new \Nocart\SharedKernel\Infrastructure\Persistence\PredisRedisClient($container->getEnv('REDIS_HOST'), $container->getEnv('int:REDIS_PORT')));
    }
}
