<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS3VUGKS\Nocart_Checkout_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS3VUGKS/Nocart_Checkout_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS3VUGKS.legacy');

    return;
}

if (!\class_exists(Nocart_Checkout_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS3VUGKS\Nocart_Checkout_KernelDevDebugContainer::class, Nocart_Checkout_KernelDevDebugContainer::class, false);
}

return new \ContainerS3VUGKS\Nocart_Checkout_KernelDevDebugContainer([
    'container.build_hash' => 'S3VUGKS',
    'container.build_id' => 'b9e73a73',
    'container.build_time' => 1770832463,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS3VUGKS');
