<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'Nocart\\Payment\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Payment\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController::getAvailable' => ['privates', '.service_locator.I8w5MxK.Nocart\\Payment\\Ports\\Http\\PaymentController::getAvailable()', 'getPaymentControllergetAvailableService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController::selectMethod' => ['privates', '.service_locator.snjpElc.Nocart\\Payment\\Ports\\Http\\PaymentController::selectMethod()', 'getPaymentControllerselectMethodService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController::getStatus' => ['privates', '.service_locator.0bEq8Oq.Nocart\\Payment\\Ports\\Http\\PaymentController::getStatus()', 'getPaymentControllergetStatusService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController::confirm' => ['privates', '.service_locator.aQLvcgi.Nocart\\Payment\\Ports\\Http\\PaymentController::confirm()', 'getPaymentControllerconfirmService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController:getAvailable' => ['privates', '.service_locator.I8w5MxK.Nocart\\Payment\\Ports\\Http\\PaymentController::getAvailable()', 'getPaymentControllergetAvailableService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController:selectMethod' => ['privates', '.service_locator.snjpElc.Nocart\\Payment\\Ports\\Http\\PaymentController::selectMethod()', 'getPaymentControllerselectMethodService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController:getStatus' => ['privates', '.service_locator.0bEq8Oq.Nocart\\Payment\\Ports\\Http\\PaymentController::getStatus()', 'getPaymentControllergetStatusService', true],
            'Nocart\\Payment\\Ports\\Http\\PaymentController:confirm' => ['privates', '.service_locator.aQLvcgi.Nocart\\Payment\\Ports\\Http\\PaymentController::confirm()', 'getPaymentControllerconfirmService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'Nocart\\Payment\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'Nocart\\Payment\\Kernel::loadRoutes' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController::getAvailable' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController::selectMethod' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController::getStatus' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController::confirm' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController:getAvailable' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController:selectMethod' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController:getStatus' => '?',
            'Nocart\\Payment\\Ports\\Http\\PaymentController:confirm' => '?',
        ]));
    }
}
