<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetPaymentStatusHandlerService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Payment\Application\Query\GetPaymentStatusHandler' shared autowired service.
     *
     * @return \Nocart\Payment\Application\Query\GetPaymentStatusHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetPaymentStatusHandler.php';

        return $container->privates['Nocart\\Payment\\Application\\Query\\GetPaymentStatusHandler'] = new \Nocart\Payment\Application\Query\GetPaymentStatusHandler(($container->privates['Nocart\\Payment\\Domain\\Repository\\PaymentSessionRepositoryInterface'] ?? $container->load('getPaymentSessionRepositoryInterfaceService')));
    }
}
