<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAvailablePaymentMethodsHandlerService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Payment\Application\Query\GetAvailablePaymentMethodsHandler' shared autowired service.
     *
     * @return \Nocart\Payment\Application\Query\GetAvailablePaymentMethodsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetAvailablePaymentMethodsHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/PaymentMethodRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemoryPaymentMethodRepository.php';

        return $container->privates['Nocart\\Payment\\Application\\Query\\GetAvailablePaymentMethodsHandler'] = new \Nocart\Payment\Application\Query\GetAvailablePaymentMethodsHandler(($container->privates['Nocart\\Payment\\Domain\\Repository\\PaymentMethodRepositoryInterface'] ??= new \Nocart\Payment\Infrastructure\Persistence\InMemoryPaymentMethodRepository()));
    }
}
