<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerconfirmService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aQLvcgi.Nocart\Payment\Ports\Http\PaymentController::confirm()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aQLvcgi.Nocart\\Payment\\Ports\\Http\\PaymentController::confirm()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionRepository' => ['privates', 'Nocart\\Payment\\Domain\\Repository\\PaymentSessionRepositoryInterface', 'getPaymentSessionRepositoryInterfaceService', true],
            'redis' => ['privates', 'Nocart\\SharedKernel\\Infrastructure\\Persistence\\RedisClientInterface', 'getRedisClientInterfaceService', true],
        ], [
            'sessionRepository' => 'Nocart\\Payment\\Domain\\Repository\\PaymentSessionRepositoryInterface',
            'redis' => 'Nocart\\SharedKernel\\Infrastructure\\Persistence\\RedisClientInterface',
        ]))->withContext('Nocart\\Payment\\Ports\\Http\\PaymentController::confirm()', $container);
    }
}
