<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllergetStatusService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0bEq8Oq.Nocart\Payment\Ports\Http\PaymentController::getStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0bEq8Oq.Nocart\\Payment\\Ports\\Http\\PaymentController::getStatus()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Payment\\Application\\Query\\GetPaymentStatusHandler', 'getGetPaymentStatusHandlerService', true],
        ], [
            'handler' => 'Nocart\\Payment\\Application\\Query\\GetPaymentStatusHandler',
        ]))->withContext('Nocart\\Payment\\Ports\\Http\\PaymentController::getStatus()', $container);
    }
}
