<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerselectMethodService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.snjpElc.Nocart\Payment\Ports\Http\PaymentController::selectMethod()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.snjpElc.Nocart\\Payment\\Ports\\Http\\PaymentController::selectMethod()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Payment\\Application\\Command\\SelectPaymentMethodHandler', 'getSelectPaymentMethodHandlerService', true],
        ], [
            'handler' => 'Nocart\\Payment\\Application\\Command\\SelectPaymentMethodHandler',
        ]))->withContext('Nocart\\Payment\\Ports\\Http\\PaymentController::selectMethod()', $container);
    }
}
