<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentSessionRepositoryInterfaceService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Payment\Domain\Repository\PaymentSessionRepositoryInterface' shared autowired service.
     *
     * @return \Nocart\Payment\Infrastructure\Persistence\RedisPaymentSessionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/PaymentSessionRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/RedisPaymentSessionRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/RedisClientInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/PredisRedisClient.php';

        return $container->privates['Nocart\\Payment\\Domain\\Repository\\PaymentSessionRepositoryInterface'] = new \Nocart\Payment\Infrastructure\Persistence\RedisPaymentSessionRepository(($container->privates['Nocart\\SharedKernel\\Infrastructure\\Persistence\\RedisClientInterface'] ??= new \Nocart\SharedKernel\Infrastructure\Persistence\PredisRedisClient($container->getEnv('REDIS_HOST'), $container->getEnv('int:REDIS_PORT'))));
    }
}
