<?php

namespace ContainerKaeE3b3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the public 'Nocart\Payment\Ports\Http\PaymentController' shared autowired service.
     *
     * @return \Nocart\Payment\Ports\Http\PaymentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Ports/Http/PaymentController.php';

        $container->services['Nocart\\Payment\\Ports\\Http\\PaymentController'] = $instance = new \Nocart\Payment\Ports\Http\PaymentController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('Nocart\\Payment\\Ports\\Http\\PaymentController', $container));

        return $instance;
    }
}
