<?php

namespace ContainerLJ6ivEf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7kBYkzGService extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7kBYkzG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7kBYkzG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Services\\Application\\Query\\GetAvailableServicesHandler', 'getGetAvailableServicesHandlerService', true],
        ], [
            'handler' => 'Nocart\\Services\\Application\\Query\\GetAvailableServicesHandler',
        ]);
    }
}
