<?php

namespace ContainerLJ6ivEf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'Nocart\\Services\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Services\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Services\\Ports\\Http\\ServicesController::getAvailable' => ['privates', '.service_locator.7kBYkzG.Nocart\\Services\\Ports\\Http\\ServicesController::getAvailable()', 'getServicesControllergetAvailableService', true],
            'Nocart\\Services\\Ports\\Http\\ServicesController::getStandalone' => ['privates', '.service_locator.7kBYkzG.Nocart\\Services\\Ports\\Http\\ServicesController::getStandalone()', 'getServicesControllergetStandaloneService', true],
            'Nocart\\Services\\Ports\\Http\\ServicesController::getForItem' => ['privates', '.service_locator.yNiQi1r.Nocart\\Services\\Ports\\Http\\ServicesController::getForItem()', 'getServicesControllergetForItemService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Services\\Ports\\Http\\ServicesController:getAvailable' => ['privates', '.service_locator.7kBYkzG.Nocart\\Services\\Ports\\Http\\ServicesController::getAvailable()', 'getServicesControllergetAvailableService', true],
            'Nocart\\Services\\Ports\\Http\\ServicesController:getStandalone' => ['privates', '.service_locator.7kBYkzG.Nocart\\Services\\Ports\\Http\\ServicesController::getStandalone()', 'getServicesControllergetStandaloneService', true],
            'Nocart\\Services\\Ports\\Http\\ServicesController:getForItem' => ['privates', '.service_locator.yNiQi1r.Nocart\\Services\\Ports\\Http\\ServicesController::getForItem()', 'getServicesControllergetForItemService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'Nocart\\Services\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'Nocart\\Services\\Kernel::loadRoutes' => '?',
            'Nocart\\Services\\Ports\\Http\\ServicesController::getAvailable' => '?',
            'Nocart\\Services\\Ports\\Http\\ServicesController::getStandalone' => '?',
            'Nocart\\Services\\Ports\\Http\\ServicesController::getForItem' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'Nocart\\Services\\Ports\\Http\\ServicesController:getAvailable' => '?',
            'Nocart\\Services\\Ports\\Http\\ServicesController:getStandalone' => '?',
            'Nocart\\Services\\Ports\\Http\\ServicesController:getForItem' => '?',
        ]));
    }
}
