<?php

namespace ContainerLJ6ivEf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesControllerService extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the public 'Nocart\Services\Ports\Http\ServicesController' shared autowired service.
     *
     * @return \Nocart\Services\Ports\Http\ServicesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Ports/Http/ServicesController.php';

        $container->services['Nocart\\Services\\Ports\\Http\\ServicesController'] = $instance = new \Nocart\Services\Ports\Http\ServicesController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('Nocart\\Services\\Ports\\Http\\ServicesController', $container));

        return $instance;
    }
}
