<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_A_WtS_Service extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.A_.WtS.' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.A_.WtS.'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['Nocart\\Shipping\\Application\\Query\\GetShippingSessionHandler'] ?? $container->load('getGetShippingSessionHandlerService')), []);
    }
}
