<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'Nocart\\Shipping\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Shipping\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::getAvailable' => ['privates', '.service_locator.G20I98l.Nocart\\Shipping\\Ports\\Http\\ShippingController::getAvailable()', 'getShippingControllergetAvailableService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::selectMethod' => ['privates', '.service_locator.KEPAcAT.Nocart\\Shipping\\Ports\\Http\\ShippingController::selectMethod()', 'getShippingControllerselectMethodService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::setAddress' => ['privates', '.service_locator.1Jbwmsx.Nocart\\Shipping\\Ports\\Http\\ShippingController::setAddress()', 'getShippingControllersetAddressService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::getSession' => ['privates', '.service_locator.LQVrDi4.Nocart\\Shipping\\Ports\\Http\\ShippingController::getSession()', 'getShippingControllergetSessionService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::setDeliveryDate' => ['privates', '.service_locator.sYNqoX_.Nocart\\Shipping\\Ports\\Http\\ShippingController::setDeliveryDate()', 'getShippingControllersetDeliveryDateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:getAvailable' => ['privates', '.service_locator.G20I98l.Nocart\\Shipping\\Ports\\Http\\ShippingController::getAvailable()', 'getShippingControllergetAvailableService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:selectMethod' => ['privates', '.service_locator.KEPAcAT.Nocart\\Shipping\\Ports\\Http\\ShippingController::selectMethod()', 'getShippingControllerselectMethodService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:setAddress' => ['privates', '.service_locator.1Jbwmsx.Nocart\\Shipping\\Ports\\Http\\ShippingController::setAddress()', 'getShippingControllersetAddressService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:getSession' => ['privates', '.service_locator.LQVrDi4.Nocart\\Shipping\\Ports\\Http\\ShippingController::getSession()', 'getShippingControllergetSessionService', true],
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:setDeliveryDate' => ['privates', '.service_locator.sYNqoX_.Nocart\\Shipping\\Ports\\Http\\ShippingController::setDeliveryDate()', 'getShippingControllersetDeliveryDateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'Nocart\\Shipping\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'Nocart\\Shipping\\Kernel::loadRoutes' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::getAvailable' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::selectMethod' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::setAddress' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::getSession' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController::setDeliveryDate' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:getAvailable' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:selectMethod' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:setAddress' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:getSession' => '?',
            'Nocart\\Shipping\\Ports\\Http\\ShippingController:setDeliveryDate' => '?',
        ]));
    }
}
