<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetShippingSessionHandlerService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Shipping\Application\Query\GetShippingSessionHandler' shared autowired service.
     *
     * @return \Nocart\Shipping\Application\Query\GetShippingSessionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetShippingSessionHandler.php';

        return $container->privates['Nocart\\Shipping\\Application\\Query\\GetShippingSessionHandler'] = new \Nocart\Shipping\Application\Query\GetShippingSessionHandler(($container->privates['Nocart\\Shipping\\Domain\\Repository\\ShippingSessionRepositoryInterface'] ?? $container->load('getShippingSessionRepositoryInterfaceService')));
    }
}
