<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthControllerService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the public 'Nocart\Shipping\Ports\Http\HealthController' shared autowired service.
     *
     * @return \Nocart\Shipping\Ports\Http\HealthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Ports/Http/HealthController.php';

        $container->services['Nocart\\Shipping\\Ports\\Http\\HealthController'] = $instance = new \Nocart\Shipping\Ports\Http\HealthController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('Nocart\\Shipping\\Ports\\Http\\HealthController', $container));

        return $instance;
    }
}
