<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingControllersetAddressService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1Jbwmsx.Nocart\Shipping\Ports\Http\ShippingController::setAddress()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1Jbwmsx.Nocart\\Shipping\\Ports\\Http\\ShippingController::setAddress()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Shipping\\Application\\Command\\SetShippingAddressHandler', 'getSetShippingAddressHandlerService', true],
        ], [
            'handler' => 'Nocart\\Shipping\\Application\\Command\\SetShippingAddressHandler',
        ]))->withContext('Nocart\\Shipping\\Ports\\Http\\ShippingController::setAddress()', $container);
    }
}
