<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingSessionRepositoryInterfaceService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Shipping\Domain\Repository\ShippingSessionRepositoryInterface' shared autowired service.
     *
     * @return \Nocart\Shipping\Infrastructure\Persistence\RedisShippingSessionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/ShippingSessionRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/RedisShippingSessionRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/RedisClientInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/PredisRedisClient.php';

        return $container->privates['Nocart\\Shipping\\Domain\\Repository\\ShippingSessionRepositoryInterface'] = new \Nocart\Shipping\Infrastructure\Persistence\RedisShippingSessionRepository(new \Nocart\SharedKernel\Infrastructure\Persistence\PredisRedisClient($container->getEnv('REDIS_HOST'), $container->getEnv('int:REDIS_PORT')));
    }
}
