<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingControllergetSessionService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LQVrDi4.Nocart\Shipping\Ports\Http\ShippingController::getSession()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LQVrDi4.Nocart\\Shipping\\Ports\\Http\\ShippingController::getSession()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Shipping\\Application\\Query\\GetShippingSessionHandler', 'getGetShippingSessionHandlerService', true],
        ], [
            'handler' => 'Nocart\\Shipping\\Application\\Query\\GetShippingSessionHandler',
        ]))->withContext('Nocart\\Shipping\\Ports\\Http\\ShippingController::getSession()', $container);
    }
}
