<?php

namespace ContainerWlo1eto;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectShippingMethodHandlerService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Shipping\Application\Command\SelectShippingMethodHandler' shared autowired service.
     *
     * @return \Nocart\Shipping\Application\Command\SelectShippingMethodHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Command/SelectShippingMethodHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/ShippingMethodRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemoryShippingMethodRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/EventPublisherInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/KafkaEventPublisher.php';

        return $container->privates['Nocart\\Shipping\\Application\\Command\\SelectShippingMethodHandler'] = new \Nocart\Shipping\Application\Command\SelectShippingMethodHandler(($container->privates['Nocart\\Shipping\\Domain\\Repository\\ShippingMethodRepositoryInterface'] ??= new \Nocart\Shipping\Infrastructure\Persistence\InMemoryShippingMethodRepository()), ($container->privates['Nocart\\Shipping\\Domain\\Repository\\ShippingSessionRepositoryInterface'] ?? $container->load('getShippingSessionRepositoryInterfaceService')), ($container->privates['Nocart\\SharedKernel\\Infrastructure\\Messaging\\EventPublisherInterface'] ??= new \Nocart\SharedKernel\Infrastructure\Messaging\KafkaEventPublisher($container->getEnv('KAFKA_BROKERS'))));
    }
}
