<?php

namespace ContainerPOCrSYA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'Nocart\\Promotion\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Promotion\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::getAvailable' => ['privates', '.service_locator.FJUrFJ9.Nocart\\Promotion\\Ports\\Http\\PromotionController::getAvailable()', 'getPromotionControllergetAvailableService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::apply' => ['privates', '.service_locator.5QzEBg3.Nocart\\Promotion\\Ports\\Http\\PromotionController::apply()', 'getPromotionControllerapplyService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::applyCode' => ['privates', '.service_locator.VxGge0X.Nocart\\Promotion\\Ports\\Http\\PromotionController::applyCode()', 'getPromotionControllerapplyCodeService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::getSession' => ['privates', '.service_locator.ZAKbgBb.Nocart\\Promotion\\Ports\\Http\\PromotionController::getSession()', 'getPromotionControllergetSessionService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:getAvailable' => ['privates', '.service_locator.FJUrFJ9.Nocart\\Promotion\\Ports\\Http\\PromotionController::getAvailable()', 'getPromotionControllergetAvailableService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:apply' => ['privates', '.service_locator.5QzEBg3.Nocart\\Promotion\\Ports\\Http\\PromotionController::apply()', 'getPromotionControllerapplyService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:applyCode' => ['privates', '.service_locator.VxGge0X.Nocart\\Promotion\\Ports\\Http\\PromotionController::applyCode()', 'getPromotionControllerapplyCodeService', true],
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:getSession' => ['privates', '.service_locator.ZAKbgBb.Nocart\\Promotion\\Ports\\Http\\PromotionController::getSession()', 'getPromotionControllergetSessionService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'Nocart\\Promotion\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'Nocart\\Promotion\\Kernel::loadRoutes' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::getAvailable' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::apply' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::applyCode' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController::getSession' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:getAvailable' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:apply' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:applyCode' => '?',
            'Nocart\\Promotion\\Ports\\Http\\PromotionController:getSession' => '?',
        ]));
    }
}
