<?php

namespace ContainerPOCrSYA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetPromotionSessionHandlerService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Promotion\Application\Query\GetPromotionSessionHandler' shared autowired service.
     *
     * @return \Nocart\Promotion\Application\Query\GetPromotionSessionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetPromotionSessionHandler.php';

        return $container->privates['Nocart\\Promotion\\Application\\Query\\GetPromotionSessionHandler'] = new \Nocart\Promotion\Application\Query\GetPromotionSessionHandler(($container->privates['Nocart\\Promotion\\Domain\\Repository\\PromotionSessionRepositoryInterface'] ?? $container->load('getPromotionSessionRepositoryInterfaceService')));
    }
}
