<?php

namespace ContainerPOCrSYA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionControllergetSessionService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZAKbgBb.Nocart\Promotion\Ports\Http\PromotionController::getSession()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZAKbgBb.Nocart\\Promotion\\Ports\\Http\\PromotionController::getSession()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Promotion\\Application\\Query\\GetPromotionSessionHandler', 'getGetPromotionSessionHandlerService', true],
        ], [
            'handler' => 'Nocart\\Promotion\\Application\\Query\\GetPromotionSessionHandler',
        ]))->withContext('Nocart\\Promotion\\Ports\\Http\\PromotionController::getSession()', $container);
    }
}
