<?php

namespace ContainerPOCrSYA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionControllerService extends Nocart_Promotion_KernelDevDebugContainer
{
    /**
     * Gets the public 'Nocart\Promotion\Ports\Http\PromotionController' shared autowired service.
     *
     * @return \Nocart\Promotion\Ports\Http\PromotionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Ports/Http/PromotionController.php';

        $container->services['Nocart\\Promotion\\Ports\\Http\\PromotionController'] = $instance = new \Nocart\Promotion\Ports\Http\PromotionController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('Nocart\\Promotion\\Ports\\Http\\PromotionController', $container));

        return $instance;
    }
}
