<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrpfyAD\Nocart_Services_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrpfyAD/Nocart_Services_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFrpfyAD.legacy');

    return;
}

if (!\class_exists(Nocart_Services_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFrpfyAD\Nocart_Services_KernelDevDebugContainer::class, Nocart_Services_KernelDevDebugContainer::class, false);
}

return new \ContainerFrpfyAD\Nocart_Services_KernelDevDebugContainer([
    'container.build_hash' => 'FrpfyAD',
    'container.build_id' => '886462e0',
    'container.build_time' => 1770831872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrpfyAD');
