<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCvxatKK\Nocart_Shipping_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCvxatKK/Nocart_Shipping_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCvxatKK.legacy');

    return;
}

if (!\class_exists(Nocart_Shipping_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCvxatKK\Nocart_Shipping_KernelDevDebugContainer::class, Nocart_Shipping_KernelDevDebugContainer::class, false);
}

return new \ContainerCvxatKK\Nocart_Shipping_KernelDevDebugContainer([
    'container.build_hash' => 'CvxatKK',
    'container.build_id' => 'd38a732d',
    'container.build_time' => 1770831872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCvxatKK');
