<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHDD98YB\Nocart_Cart_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHDD98YB/Nocart_Cart_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHDD98YB.legacy');

    return;
}

if (!\class_exists(Nocart_Cart_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHDD98YB\Nocart_Cart_KernelDevDebugContainer::class, Nocart_Cart_KernelDevDebugContainer::class, false);
}

return new \ContainerHDD98YB\Nocart_Cart_KernelDevDebugContainer([
    'container.build_hash' => 'HDD98YB',
    'container.build_id' => 'e89d5892',
    'container.build_time' => 1770831698,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHDD98YB');
