<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhhYfNg\Nocart_Promotion_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhhYfNg/Nocart_Promotion_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPhhYfNg.legacy');

    return;
}

if (!\class_exists(Nocart_Promotion_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPhhYfNg\Nocart_Promotion_KernelDevDebugContainer::class, Nocart_Promotion_KernelDevDebugContainer::class, false);
}

return new \ContainerPhhYfNg\Nocart_Promotion_KernelDevDebugContainer([
    'container.build_hash' => 'PhhYfNg',
    'container.build_id' => '47df3567',
    'container.build_time' => 1770831872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhhYfNg');
