<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_MI2w8iBService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.mI2w8iB' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.mI2w8iB'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['Nocart\\Cart\\Application\\Command\\ChangeItemQuantityHandler'] ?? $container->load('getChangeItemQuantityHandlerService')), []);
    }
}
