<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Z3seoD7Service extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.z3seoD7' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.z3seoD7'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['Nocart\\Cart\\Application\\Command\\AddItemToCartHandler'] ?? $container->load('getAddItemToCartHandlerService')), []);
    }
}
