<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddItemToCartHandlerService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Cart\Application\Command\AddItemToCartHandler' shared autowired service.
     *
     * @return \Nocart\Cart\Application\Command\AddItemToCartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Command/AddItemToCartHandler.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/EventPublisherInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/KafkaEventPublisher.php';

        return $container->privates['Nocart\\Cart\\Application\\Command\\AddItemToCartHandler'] = new \Nocart\Cart\Application\Command\AddItemToCartHandler(($container->privates['Nocart\\Cart\\Domain\\Repository\\CartRepositoryInterface'] ?? $container->load('getCartRepositoryInterfaceService')), ($container->privates['Nocart\\SharedKernel\\Infrastructure\\Messaging\\EventPublisherInterface'] ??= new \Nocart\SharedKernel\Infrastructure\Messaging\KafkaEventPublisher($container->getEnv('KAFKA_BROKERS'))));
    }
}
