<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControlleraddItemService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2_iEKQk.Nocart\Cart\Ports\Http\CartController::addItem()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2_iEKQk.Nocart\\Cart\\Ports\\Http\\CartController::addItem()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Cart\\Application\\Command\\AddItemToCartHandler', 'getAddItemToCartHandlerService', true],
        ], [
            'handler' => 'Nocart\\Cart\\Application\\Command\\AddItemToCartHandler',
        ]))->withContext('Nocart\\Cart\\Ports\\Http\\CartController::addItem()', $container);
    }
}
