<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the public 'Nocart\Cart\Ports\Http\CartController' shared autowired service.
     *
     * @return \Nocart\Cart\Ports\Http\CartController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Ports/Http/BaseApiController.php';
        include_once \dirname(__DIR__, 4).'/src/Ports/Http/CartController.php';

        $container->services['Nocart\\Cart\\Ports\\Http\\CartController'] = $instance = new \Nocart\Cart\Ports\Http\CartController();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'serializer' => '?',
            'parameter_bag' => '?',
        ]))->withContext('Nocart\\Cart\\Ports\\Http\\CartController', $container));

        return $instance;
    }
}
