<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllergetCartService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nBrMJvl.Nocart\Cart\Ports\Http\CartController::getCart()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nBrMJvl.Nocart\\Cart\\Ports\\Http\\CartController::getCart()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Cart\\Application\\Query\\GetCartHandler', 'getGetCartHandlerService', true],
        ], [
            'handler' => 'Nocart\\Cart\\Application\\Query\\GetCartHandler',
        ]))->withContext('Nocart\\Cart\\Ports\\Http\\CartController::getCart()', $container);
    }
}
