<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetCartHandlerService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Cart\Application\Query\GetCartHandler' shared autowired service.
     *
     * @return \Nocart\Cart\Application\Query\GetCartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetCartHandler.php';

        return $container->privates['Nocart\\Cart\\Application\\Query\\GetCartHandler'] = new \Nocart\Cart\Application\Query\GetCartHandler(($container->privates['Nocart\\Cart\\Domain\\Repository\\CartRepositoryInterface'] ?? $container->load('getCartRepositoryInterfaceService')));
    }
}
