<?php

namespace ContainerCt8c6PA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Default_Middleware_HandleMessageService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.bus.default.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Nocart\\Cart\\Application\\Command\\AddItemToCartCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.z3seoD7'] ?? $container->load('get_Messenger_HandlerDescriptor_Z3seoD7Service'));
        }, 1), 'Nocart\\Cart\\Application\\Command\\ChangeItemQuantityCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.mI2w8iB'] ?? $container->load('get_Messenger_HandlerDescriptor_MI2w8iBService'));
        }, 1), 'Nocart\\Cart\\Application\\Command\\ClearCartCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.BvYcXD9'] ?? $container->load('get_Messenger_HandlerDescriptor_BvYcXD9Service'));
        }, 1), 'Nocart\\Cart\\Application\\Command\\RemoveItemFromCartCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.P1eU6by'] ?? $container->load('get_Messenger_HandlerDescriptor_P1eU6byService'));
        }, 1), 'Nocart\\Cart\\Application\\Query\\GetCartQuery' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.bsPC3t.'] ?? $container->load('get_Messenger_HandlerDescriptor_BsPC3t_Service'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.jyyWvHw'] ?? $container->load('get_Messenger_HandlerDescriptor_JyyWvHwService'));
        }, 1)]), false);

        if (isset($container->privates['messenger.bus.default.middleware.handle_message'])) {
            return $container->privates['messenger.bus.default.middleware.handle_message'];
        }

        $container->privates['messenger.bus.default.middleware.handle_message'] = $instance;

        $instance->setLogger(($container->privates['logger'] ?? self::getLoggerService($container)));

        return $instance;
    }
}
