<?php

namespace ContainerFrpfyAD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_A8RwQ31Service extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.A8RwQ31' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Application/MessageHandler/CartEventHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/ServicesSessionRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/RedisServicesSessionRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/RedisClientInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/PredisRedisClient.php';

        return $container->privates['.messenger.handler_descriptor.A8RwQ31'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Nocart\Services\Application\MessageHandler\CartEventHandler(new \Nocart\Services\Infrastructure\Persistence\RedisServicesSessionRepository(new \Nocart\SharedKernel\Infrastructure\Persistence\PredisRedisClient($container->getEnv('REDIS_HOST'), $container->getEnv('int:REDIS_PORT'))), ($container->privates['logger'] ?? self::getLoggerService($container))), []);
    }
}
