<?php

namespace ContainerFrpfyAD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAvailableServicesHandlerService extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Services\Application\Query\GetAvailableServicesHandler' shared autowired service.
     *
     * @return \Nocart\Services\Application\Query\GetAvailableServicesHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetAvailableServicesHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/AdditionalServiceRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemoryAdditionalServiceRepository.php';

        return $container->privates['Nocart\\Services\\Application\\Query\\GetAvailableServicesHandler'] = new \Nocart\Services\Application\Query\GetAvailableServicesHandler(($container->privates['Nocart\\Services\\Domain\\Repository\\AdditionalServiceRepositoryInterface'] ??= new \Nocart\Services\Infrastructure\Persistence\InMemoryAdditionalServiceRepository()));
    }
}
