<?php

namespace ContainerFrpfyAD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_ReceiverLocatorService extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.receiver_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.receiver_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messenger.transport.kafka_consumer' => ['privates', 'messenger.transport.kafka_consumer', 'getMessenger_Transport_KafkaConsumerService', true],
            'kafka_consumer' => ['privates', 'messenger.transport.kafka_consumer', 'getMessenger_Transport_KafkaConsumerService', true],
        ], [
            'messenger.transport.kafka_consumer' => '?',
            'kafka_consumer' => '?',
        ]);
    }
}
