<?php

namespace ContainerFrpfyAD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesControllergetAvailableService extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7kBYkzG.Nocart\Services\Ports\Http\ServicesController::getAvailable()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7kBYkzG.Nocart\\Services\\Ports\\Http\\ServicesController::getAvailable()'] = ($container->privates['.service_locator.7kBYkzG'] ?? $container->load('get_ServiceLocator_7kBYkzGService'))->withContext('Nocart\\Services\\Ports\\Http\\ServicesController::getAvailable()', $container);
    }
}
