<?php

namespace ContainerFrpfyAD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesControllergetForItemService extends Nocart_Services_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yNiQi1r.Nocart\Services\Ports\Http\ServicesController::getForItem()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yNiQi1r.Nocart\\Services\\Ports\\Http\\ServicesController::getForItem()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Services\\Application\\Query\\GetServicesForItemHandler', 'getGetServicesForItemHandlerService', true],
        ], [
            'handler' => 'Nocart\\Services\\Application\\Query\\GetServicesForItemHandler',
        ]))->withContext('Nocart\\Services\\Ports\\Http\\ServicesController::getForItem()', $container);
    }
}
