<?php

namespace ContainerGNEnspg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor__3Nw4FTService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor..3Nw4FT' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor..3Nw4FT'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['Nocart\\Payment\\Application\\Query\\GetPaymentStatusHandler'] ?? $container->load('getGetPaymentStatusHandlerService')), []);
    }
}
