<?php

namespace ContainerGNEnspg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllergetAvailableService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I8w5MxK.Nocart\Payment\Ports\Http\PaymentController::getAvailable()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I8w5MxK.Nocart\\Payment\\Ports\\Http\\PaymentController::getAvailable()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Payment\\Application\\Query\\GetAvailablePaymentMethodsHandler', 'getGetAvailablePaymentMethodsHandlerService', true],
        ], [
            'handler' => 'Nocart\\Payment\\Application\\Query\\GetAvailablePaymentMethodsHandler',
        ]))->withContext('Nocart\\Payment\\Ports\\Http\\PaymentController::getAvailable()', $container);
    }
}
