<?php

namespace ContainerGNEnspg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectPaymentMethodHandlerService extends Nocart_Payment_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Payment\Application\Command\SelectPaymentMethodHandler' shared autowired service.
     *
     * @return \Nocart\Payment\Application\Command\SelectPaymentMethodHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Command/SelectPaymentMethodHandler.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/EventPublisherInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/KafkaEventPublisher.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/PaymentMethodRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemoryPaymentMethodRepository.php';

        return $container->privates['Nocart\\Payment\\Application\\Command\\SelectPaymentMethodHandler'] = new \Nocart\Payment\Application\Command\SelectPaymentMethodHandler(($container->privates['Nocart\\Payment\\Domain\\Repository\\PaymentMethodRepositoryInterface'] ??= new \Nocart\Payment\Infrastructure\Persistence\InMemoryPaymentMethodRepository()), ($container->privates['Nocart\\Payment\\Domain\\Repository\\PaymentSessionRepositoryInterface'] ?? $container->load('getPaymentSessionRepositoryInterfaceService')), new \Nocart\SharedKernel\Infrastructure\Messaging\KafkaEventPublisher($container->getEnv('KAFKA_BROKERS')));
    }
}
