<?php

namespace ContainerHDD98YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'Nocart\\Cart\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Cart\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController::getCart' => ['privates', '.service_locator.nBrMJvl.Nocart\\Cart\\Ports\\Http\\CartController::getCart()', 'getCartControllergetCartService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController::addItem' => ['privates', '.service_locator.2_iEKQk.Nocart\\Cart\\Ports\\Http\\CartController::addItem()', 'getCartControlleraddItemService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController::removeItem' => ['privates', '.service_locator.P3778pw.Nocart\\Cart\\Ports\\Http\\CartController::removeItem()', 'getCartControllerremoveItemService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController::changeQuantity' => ['privates', '.service_locator.FtKrkUp.Nocart\\Cart\\Ports\\Http\\CartController::changeQuantity()', 'getCartControllerchangeQuantityService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController::clearCart' => ['privates', '.service_locator.tRW_oIj.Nocart\\Cart\\Ports\\Http\\CartController::clearCart()', 'getCartControllerclearCartService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController:getCart' => ['privates', '.service_locator.nBrMJvl.Nocart\\Cart\\Ports\\Http\\CartController::getCart()', 'getCartControllergetCartService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController:addItem' => ['privates', '.service_locator.2_iEKQk.Nocart\\Cart\\Ports\\Http\\CartController::addItem()', 'getCartControlleraddItemService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController:removeItem' => ['privates', '.service_locator.P3778pw.Nocart\\Cart\\Ports\\Http\\CartController::removeItem()', 'getCartControllerremoveItemService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController:changeQuantity' => ['privates', '.service_locator.FtKrkUp.Nocart\\Cart\\Ports\\Http\\CartController::changeQuantity()', 'getCartControllerchangeQuantityService', true],
            'Nocart\\Cart\\Ports\\Http\\CartController:clearCart' => ['privates', '.service_locator.tRW_oIj.Nocart\\Cart\\Ports\\Http\\CartController::clearCart()', 'getCartControllerclearCartService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'Nocart\\Cart\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'Nocart\\Cart\\Kernel::loadRoutes' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController::getCart' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController::addItem' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController::removeItem' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController::changeQuantity' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController::clearCart' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController:getCart' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController:addItem' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController:removeItem' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController:changeQuantity' => '?',
            'Nocart\\Cart\\Ports\\Http\\CartController:clearCart' => '?',
        ]));
    }
}
