<?php

namespace ContainerHDD98YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartRepositoryInterfaceService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Cart\Domain\Repository\CartRepositoryInterface' shared autowired service.
     *
     * @return \Nocart\Cart\Infrastructure\Persistence\RedisCartRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/CartRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/RedisCartRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/RedisClientInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/PredisRedisClient.php';

        return $container->privates['Nocart\\Cart\\Domain\\Repository\\CartRepositoryInterface'] = new \Nocart\Cart\Infrastructure\Persistence\RedisCartRepository(new \Nocart\SharedKernel\Infrastructure\Persistence\PredisRedisClient($container->getEnv('REDIS_HOST'), $container->getEnv('int:REDIS_PORT')));
    }
}
