<?php

namespace ContainerHDD98YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_MessengerDebugService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.messenger_debug' shared service.
     *
     * @return \Symfony\Component\Messenger\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Command/DebugCommand.php';

        $container->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['messenger.bus.default' => ['Nocart\\Cart\\Application\\Command\\AddItemToCartCommand' => [['Nocart\\Cart\\Application\\Command\\AddItemToCartHandler', []]], 'Nocart\\Cart\\Application\\Command\\ChangeItemQuantityCommand' => [['Nocart\\Cart\\Application\\Command\\ChangeItemQuantityHandler', []]], 'Nocart\\Cart\\Application\\Command\\ClearCartCommand' => [['Nocart\\Cart\\Application\\Command\\ClearCartHandler', []]], 'Nocart\\Cart\\Application\\Command\\RemoveItemFromCartCommand' => [['Nocart\\Cart\\Application\\Command\\RemoveItemFromCartHandler', []]], 'Nocart\\Cart\\Application\\Query\\GetCartQuery' => [['Nocart\\Cart\\Application\\Query\\GetCartHandler', []]], 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => [['console.messenger.execute_command_handler', ['sign' => true]]], 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => [['messenger.redispatch_message_handler', []]]]]);

        $instance->setName('debug:messenger');
        $instance->setDescription('List messages you can dispatch using the message buses');

        return $instance;
    }
}
