<?php

namespace ContainerHDD98YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerchangeQuantityService extends Nocart_Cart_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FtKrkUp.Nocart\Cart\Ports\Http\CartController::changeQuantity()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FtKrkUp.Nocart\\Cart\\Ports\\Http\\CartController::changeQuantity()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Cart\\Application\\Command\\ChangeItemQuantityHandler', 'getChangeItemQuantityHandlerService', true],
        ], [
            'handler' => 'Nocart\\Cart\\Application\\Command\\ChangeItemQuantityHandler',
        ]))->withContext('Nocart\\Cart\\Ports\\Http\\CartController::changeQuantity()', $container);
    }
}
