<?php

namespace ContainerS3VUGKS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BsIQhrService extends Nocart_Checkout_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bs_IQhr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kafka_consumer' => ['privates', 'messenger.transport.kafka_consumer', 'getMessenger_Transport_KafkaConsumerService', true],
            'messenger.transport.kafka_consumer' => ['privates', 'messenger.transport.kafka_consumer', 'getMessenger_Transport_KafkaConsumerService', true],
        ], [
            'kafka_consumer' => '?',
            'messenger.transport.kafka_consumer' => '?',
        ]);

        if (isset($container->privates['.service_locator.Bs_IQhr'])) {
            return $container->privates['.service_locator.Bs_IQhr'];
        }

        return $container->privates['.service_locator.Bs_IQhr'] = $instance;
    }
}
