<?php

namespace ContainerS3VUGKS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_BG7hCqGService extends Nocart_Checkout_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.BG7hCqG' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Application/MessageHandler/ExternalEventHandler.php';

        return $container->privates['.messenger.handler_descriptor.BG7hCqG'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Nocart\Checkout\Application\MessageHandler\ExternalEventHandler(($container->privates['Nocart\\Checkout\\Domain\\Repository\\CheckoutOrderRepositoryInterface'] ?? $container->load('getCheckoutOrderRepositoryInterfaceService')), ($container->privates['logger'] ?? self::getLoggerService($container))), []);
    }
}
