<?php

namespace ContainerS3VUGKS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutOrderRepositoryInterfaceService extends Nocart_Checkout_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Checkout\Domain\Repository\CheckoutOrderRepositoryInterface' shared autowired service.
     *
     * @return \Nocart\Checkout\Infrastructure\Persistence\RedisCheckoutOrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/CheckoutOrderRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/RedisCheckoutOrderRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/RedisClientInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/PredisRedisClient.php';

        return $container->privates['Nocart\\Checkout\\Domain\\Repository\\CheckoutOrderRepositoryInterface'] = new \Nocart\Checkout\Infrastructure\Persistence\RedisCheckoutOrderRepository(($container->privates['Nocart\\SharedKernel\\Infrastructure\\Persistence\\RedisClientInterface'] ??= new \Nocart\SharedKernel\Infrastructure\Persistence\PredisRedisClient($container->getEnv('REDIS_HOST'), $container->getEnv('int:REDIS_PORT'))));
    }
}
