<?php

namespace ContainerS3VUGKS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllergetTotalsService extends Nocart_Checkout_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fMry7lA.Nocart\Checkout\Ports\Http\CheckoutController::getTotals()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fMry7lA.Nocart\\Checkout\\Ports\\Http\\CheckoutController::getTotals()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Checkout\\Application\\Query\\GetCheckoutTotalsHandler', 'getGetCheckoutTotalsHandlerService', true],
        ], [
            'handler' => 'Nocart\\Checkout\\Application\\Query\\GetCheckoutTotalsHandler',
        ]))->withContext('Nocart\\Checkout\\Ports\\Http\\CheckoutController::getTotals()', $container);
    }
}
