<?php

namespace ContainerS3VUGKS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllerService extends Nocart_Checkout_KernelDevDebugContainer
{
    /**
     * Gets the public 'Nocart\Checkout\Ports\Http\CheckoutController' shared autowired service.
     *
     * @return \Nocart\Checkout\Ports\Http\CheckoutController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Ports/Http/CheckoutController.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/CheckoutSessionRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/RedisCheckoutSessionRepository.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/RedisClientInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Persistence/PredisRedisClient.php';

        $container->services['Nocart\\Checkout\\Ports\\Http\\CheckoutController'] = $instance = new \Nocart\Checkout\Ports\Http\CheckoutController(new \Nocart\Checkout\Infrastructure\Persistence\RedisCheckoutSessionRepository(($container->privates['Nocart\\SharedKernel\\Infrastructure\\Persistence\\RedisClientInterface'] ??= new \Nocart\SharedKernel\Infrastructure\Persistence\PredisRedisClient($container->getEnv('REDIS_HOST'), $container->getEnv('int:REDIS_PORT')))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('Nocart\\Checkout\\Ports\\Http\\CheckoutController', $container));

        return $instance;
    }
}
