<?php

namespace ContainerS3VUGKS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetCheckoutTotalsHandlerService extends Nocart_Checkout_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Checkout\Application\Query\GetCheckoutTotalsHandler' shared autowired service.
     *
     * @return \Nocart\Checkout\Application\Query\GetCheckoutTotalsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetCheckoutTotalsHandler.php';

        return $container->privates['Nocart\\Checkout\\Application\\Query\\GetCheckoutTotalsHandler'] = new \Nocart\Checkout\Application\Query\GetCheckoutTotalsHandler(($container->privates['Nocart\\Checkout\\Domain\\Repository\\CheckoutOrderRepositoryInterface'] ?? $container->load('getCheckoutOrderRepositoryInterfaceService')), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
