<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGNEnspg\Nocart_Payment_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGNEnspg/Nocart_Payment_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGNEnspg.legacy');

    return;
}

if (!\class_exists(Nocart_Payment_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGNEnspg\Nocart_Payment_KernelDevDebugContainer::class, Nocart_Payment_KernelDevDebugContainer::class, false);
}

return new \ContainerGNEnspg\Nocart_Payment_KernelDevDebugContainer([
    'container.build_hash' => 'GNEnspg',
    'container.build_id' => 'a64550d1',
    'container.build_time' => 1770831872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGNEnspg');
