<?php

namespace ContainerCvxatKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_U7TAOg2Service extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.U7TAOg2' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Application/MessageHandler/CartEventHandler.php';

        return $container->privates['.messenger.handler_descriptor.U7TAOg2'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Nocart\Shipping\Application\MessageHandler\CartEventHandler(($container->privates['Nocart\\Shipping\\Domain\\Repository\\ShippingSessionRepositoryInterface'] ?? $container->load('getShippingSessionRepositoryInterfaceService')), ($container->privates['logger'] ?? self::getLoggerService($container))), []);
    }
}
