<?php

namespace ContainerCvxatKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAvailableShippingMethodsHandlerService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Shipping\Application\Query\GetAvailableShippingMethodsHandler' shared autowired service.
     *
     * @return \Nocart\Shipping\Application\Query\GetAvailableShippingMethodsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Query/GetAvailableShippingMethodsHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/ShippingMethodRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemoryShippingMethodRepository.php';

        return $container->privates['Nocart\\Shipping\\Application\\Query\\GetAvailableShippingMethodsHandler'] = new \Nocart\Shipping\Application\Query\GetAvailableShippingMethodsHandler(($container->privates['Nocart\\Shipping\\Domain\\Repository\\ShippingMethodRepositoryInterface'] ??= new \Nocart\Shipping\Infrastructure\Persistence\InMemoryShippingMethodRepository()));
    }
}
