<?php

namespace ContainerCvxatKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_KafkaConsumerService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.transport.kafka_consumer' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SigningSerializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/PhpSerializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/LazyString.php';

        $instance = (new \Symfony\Component\Messenger\Transport\TransportFactory(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Nocart\\SharedKernel\\Infrastructure\\Messenger\\KafkaTransportFactory'] ??= new \Nocart\SharedKernel\Infrastructure\Messenger\KafkaTransportFactory());
            yield 1 => ($container->privates['messenger.transport.sync.factory'] ?? $container->load('getMessenger_Transport_Sync_FactoryService'));
            yield 2 => ($container->privates['messenger.transport.in_memory.factory'] ?? $container->load('getMessenger_Transport_InMemory_FactoryService'));
        }, 3)))->createTransport('kafka://'.$container->getEnv('string:KAFKA_BROKERS').'?topics=cart-events&group=shipping-consumer', ['transport_name' => 'kafka_consumer'], new \Symfony\Component\Messenger\Transport\Serialization\SigningSerializer(new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer(), \Symfony\Component\String\LazyString::fromCallable(#[\Closure(name: '.messenger.signing_serializer.signing_key', class: 'string')] fn () => ($container->privates['.messenger.signing_serializer.signing_key'] ?? $container->load('get_Messenger_SigningSerializer_SigningKeyService'))), ['Symfony\\Component\\Console\\Messenger\\RunCommandMessage']));

        if (isset($container->privates['messenger.transport.kafka_consumer'])) {
            return $container->privates['messenger.transport.kafka_consumer'];
        }

        return $container->privates['messenger.transport.kafka_consumer'] = $instance;
    }
}
