<?php

namespace ContainerCvxatKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingControllerselectMethodService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KEPAcAT.Nocart\Shipping\Ports\Http\ShippingController::selectMethod()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KEPAcAT.Nocart\\Shipping\\Ports\\Http\\ShippingController::selectMethod()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Shipping\\Application\\Command\\SelectShippingMethodHandler', 'getSelectShippingMethodHandlerService', true],
        ], [
            'handler' => 'Nocart\\Shipping\\Application\\Command\\SelectShippingMethodHandler',
        ]))->withContext('Nocart\\Shipping\\Ports\\Http\\ShippingController::selectMethod()', $container);
    }
}
