<?php

namespace ContainerCvxatKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetDeliveryDateHandlerService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nocart\Shipping\Application\Command\SetDeliveryDateHandler' shared autowired service.
     *
     * @return \Nocart\Shipping\Application\Command\SetDeliveryDateHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Command/SetDeliveryDateHandler.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/EventPublisherInterface.php';
        include_once \dirname(__DIR__, 5).'/shared/src/Infrastructure/Messaging/KafkaEventPublisher.php';

        return $container->privates['Nocart\\Shipping\\Application\\Command\\SetDeliveryDateHandler'] = new \Nocart\Shipping\Application\Command\SetDeliveryDateHandler(($container->privates['Nocart\\Shipping\\Domain\\Repository\\ShippingSessionRepositoryInterface'] ?? $container->load('getShippingSessionRepositoryInterfaceService')), ($container->privates['Nocart\\SharedKernel\\Infrastructure\\Messaging\\EventPublisherInterface'] ??= new \Nocart\SharedKernel\Infrastructure\Messaging\KafkaEventPublisher($container->getEnv('KAFKA_BROKERS'))));
    }
}
