<?php

namespace ContainerCvxatKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingControllersetDeliveryDateService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sYNqoX_.Nocart\Shipping\Ports\Http\ShippingController::setDeliveryDate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sYNqoX_.Nocart\\Shipping\\Ports\\Http\\ShippingController::setDeliveryDate()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Shipping\\Application\\Command\\SetDeliveryDateHandler', 'getSetDeliveryDateHandlerService', true],
        ], [
            'handler' => 'Nocart\\Shipping\\Application\\Command\\SetDeliveryDateHandler',
        ]))->withContext('Nocart\\Shipping\\Ports\\Http\\ShippingController::setDeliveryDate()', $container);
    }
}
