<?php

namespace ContainerCvxatKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingControllergetAvailableService extends Nocart_Shipping_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G20I98l.Nocart\Shipping\Ports\Http\ShippingController::getAvailable()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G20I98l.Nocart\\Shipping\\Ports\\Http\\ShippingController::getAvailable()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'Nocart\\Shipping\\Application\\Query\\GetAvailableShippingMethodsHandler', 'getGetAvailableShippingMethodsHandlerService', true],
        ], [
            'handler' => 'Nocart\\Shipping\\Application\\Query\\GetAvailableShippingMethodsHandler',
        ]))->withContext('Nocart\\Shipping\\Ports\\Http\\ShippingController::getAvailable()', $container);
    }
}
